Shorten PlasticSCM user names for display
SRombauts/UE4PlasticPlugin pull request #101
Opened 2022-06-02 15:35 UTC by SRombauts

Add Project Settings to configure:
- Map PlasticSCM user names (typically e-mail addresses or company domain names) to display names for brevity.
- Hide the domain part of a username e-mail address (eg @gmail.com) if the map above didn't match. Enabled by default.

Fixes #99 and #100

2022-06-04 22:01 UTC, seesemichaelj requested changes
Behavior works for the "history" for a file, but neither feature is working for the modal dialogue on a file itself showing who has it checked out

![image](https://user-images.githubusercontent.com/549323/172026754-f993c216-2558-4135-a391-aa16ab903a75.png)

2022-06-07 14:25 UTC, SRombauts commented on Source/PlasticSourceControl/Private/PlasticSourceControlProjectSettings.h
> +class UPlasticSourceControlProjectSettings : public UDeveloperSettings
Hey, let me know what you think about the latest changes when you have time.
Cheers!

2022-06-07 17:37 UTC, seesemichaelj reviewed
Works as expected! Users may need to `Right Click on asset > Source Control > Refresh` for changed mappings to take effect for the locked file.

2022-06-07 19:06 UTC, SRombauts commented
Right, I choose to call the conversion function only once when acquiring the data, instead of at each refresh of the UI
I think it's simple and understandable, but we could decide to change it if you are not convinced.

2022-06-07 19:08 UTC, seesemichaelj commented
Nope, it's totally fine as is; it was just an observation in the event users report it as a bug

2022-06-07 19:40 UTC, merged

2022-06-07 19:57 UTC, SRombauts commented
Ok, merged to master, thanks for the review & feedback 😊

2022-06-07 19:58 UTC, SRombauts commented
I shall add an entry in the Readme, but not tonight